### ISSUE TITLE
Pylance hint Import "odoo.addons.web.controllers" could not be resolved

### ISSUE THREAD

**Issue by ohplz** [cetmix/docker-odoo-debug#1]
I got pylint works fine by python.analysis.extraPaths, but Pylance still can't get it right, did u running into this?

![image](https://user-images.githubusercontent.com/46417244/227853876-0203add3-fcdc-4e6f-8a75-0639330fda0a.png)

**Comment by ivs-cetmix** [comment]
Yup but I just ingnred that for now.  Looks like we need to update the paths somehow.

![image](https://user-images.githubusercontent.com/2234999/228350042-c5603f0b-2951-44b1-9cd9-660c35c1cdb4.png)
